### PR TITLE
Enable efficiency mode for razer-tray

### PR DESCRIPTION
**Pull request by jacobgelling**
This PR enables efficiency mode for razer-tray.

It marks the process as low priority and consumes less power, perfect for a tray app running in the background.

Effect can be seen in task manager:
image

### CODE REVIEW

**Comment by tdakhran** [comment]
Thanks for your contribution! Efficiency mode is a great fit for this application.
Windows-specific things break compilation for Linux.
```shell
❯ cargo build --release
...
= note: /usr/sbin/ld: /tmp/razer-ctl/target/release/deps/razer_tray-cf05d932771d07d6.razer_tray.d705ed2d400c0810-cgu.00.rcgu.o: in function `razer_tray::main':
          razer_tray.d705ed2d400c0810-cgu.00:(.text._ZN10razer_tray4main17h542f386bec55afb4E+0x4372): undefined reference to `GetCurrentProcess'
          /usr/sbin/ld: razer_tray.d705ed2d400c0810-cgu.00:(.text._ZN10razer_tray4main17h542f386bec55afb4E+0x4383): undefined reference to `SetPriorityClass'
          /usr/sbin/ld: razer_tray.d705ed2d400c0810-cgu.00:(.text._ZN10razer_tray4main17h542f386bec55afb4E+0x438d): undefined reference to `GetLastError'
          /usr/sbin/ld: razer_tray.d705ed2d400c0810-cgu.00:(.text._ZN10razer_tray4main17h542f386bec55afb4E+0x43bc): undefined reference to `SetProcessInformation'
          /usr/sbin/ld: razer_tray.d705ed2d400c0810-cgu.00:(.text._ZN10razer_tray4main17h542f386bec55afb4E+0x43c6): undefined reference to `GetLastError'
```

I need to work on adding a bit of CI to catch such things. For now, let's guard windows specific things under [Conditional Compilation](https://doc.rust-lang.org/reference/conditional-compilation.html).

**Comment by jacobgelling** [comment]
@tdakhran I've added the conditional compilation flags and conditional windows crate dependency.

**Comment by tdakhran** [comment]
Thanks!
Build for Linux still fails
```
❯ cargo build --release
   Compiling razer-tray v0.6.0 (/tmp/razer-ctl/razer-tray)
error[E0425]: cannot find function `efficiency_mode` in this scope
   --> razer-tray/src/main.rs:626:9
    |
626 |         efficiency_mode();
    |         ^^^^^^^^^^^^^^^ not found in this scope
```
It should be something like to completely disable the code
```
    #[cfg(target_os = "windows")]
    efficiency_mode();
```

I merged #1 and this got automatically closed. And I can't reopen it again. @jacobgelling could you please resubmit the PR? You have contributor access and can create PR directly in this repo.

**Comment by tdakhran** [comment]
I reopened https://github.com/tdakhran/razer-ctl/tree/tarek/feat/support_razer_blade_14_2023, but I can't retarget this PR to https://github.com/tdakhran/razer-ctl/tree/main

**Pull request closed without merging**
